name: vlock-ci

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  schedule:
  - cron: '13 1 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --verbose
